name: Build & Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci || npm install
        else
          npm install
        fi

    - name: Typecheck / Lint Codebase
      run: npm run lint

    - name: Build Production Assets
      run: npm run build
